pipeline {
    agent any
    stages {
        stage('Initialize'){
            steps {
                echo "Docker processes"
                sh "docker ps -a"

                echo "Docker images"
                sh "docker images"
            }
        }
        stage('Docker image build'){
            steps {
                echo "Docker build is starting up...."

                sh "cd challange_2_megoldas && ls -al && docker build -t barrekft/zoli:build_from_jenkins ."

                echo "...docker build is done!"
            }
        }
    }
}
