pipeline {
    agent any
    stages {
        stage('Initialize'){
            steps {
                echo "Docker processes"
                sh "docker ps -a"

                echo "Docker images"
                sh "docker images"
            }
        }
        stage('Docker image build'){
            steps {
                echo "Docker build is starting up...."

                sh "cd challange_2_megoldas && ls -al && docker build -t barrekft/zoli:${env.BUILD_ID} ."

                echo "...docker build is done!"
                sh "docker images"
            }
        }
        stage('Startup new image'){
            steps {
                echo "Docker run"

                sh "docker run -d -p 8090:80 barrekft/zoli:${env.BUILD_ID}"

                echo "Deployment done"
            }
        }
    }
}
